# Generated by Django 3.0 on 2021-10-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_publicaciones_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='categoria',
            field=models.ManyToManyField(related_name='get_publicaciones', to='blog.categorias'),
        ),
    ]
