# Generated by Django 3.0 on 2021-10-21 03:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211017_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicaciones',
            name='contenido',
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='Contenido',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Contenido'),
            preserve_default=False,
        ),
    ]
