# Generated by Django 3.0 on 2021-10-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_paquete_contenido'),
        ('blog', '0004_auto_20211020_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='paquete',
            field=models.ManyToManyField(to='package.paquete'),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='categoria',
            field=models.ManyToManyField(to='blog.categorias'),
        ),
    ]
