# Generated by Django 3.0 on 2021-10-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211021_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='imagen',
            field=models.ImageField(null=True, upload_to='blog'),
        ),
    ]
