# Generated by Django 3.0 on 2021-10-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20211021_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='imagen',
            field=models.ImageField(default=1, upload_to='blog'),
            preserve_default=False,
        ),
    ]
