# Generated by Django 3.0 on 2021-10-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='imagen',
            field=models.ImageField(default=1, upload_to='package'),
            preserve_default=False,
        ),
    ]
