# Generated by Django 3.0 on 2021-10-19 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('package', '0002_paquete_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoriaPaquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'categoria_P',
                'db_table': 'categoria',
            },
        ),
        migrations.AddField(
            model_name='paquete',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paquete',
            name='categoria',
            field=models.ManyToManyField(related_name='get_paquetes', to='package.categoriaPaquete'),
        ),
    ]
