# Generated by Django 3.0 on 2021-10-21 03:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_auto_20211018_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='Contenido',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Contenido'),
            preserve_default=False,
        ),
    ]
