# Generated by Django 3.0 on 2021-10-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_paquete_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='imagen',
            field=models.ImageField(null=True, upload_to='package'),
        ),
    ]
