# Generated by Django 3.0 on 2021-10-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_auto_20211021_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='imagen',
            field=models.ImageField(default=1, upload_to='package'),
            preserve_default=False,
        ),
    ]
